# Copyright 2012 Dorival de Moraes Pedroso. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

FNKEY=rel-prob1to5
#FNKEY=rel-prob6

all: $(FNKEY)

$(FNKEY):
	go build -o /tmp/goga/$(FNKEY) $(FNKEY).go && /tmp/goga/$(FNKEY)
